### ISSUE TITLE
Cherry-pick aborts when merge conflicts

### ISSUE THREAD

**Issue by protoEvangelion** [drewbrokke/jack-cli#17] opened 2017-08-10 15:15 UTC
Is it the intended functionality for cherry-picks to abort when there are merge conflicts?

The message that pops up when the cherry-pick fails suggests that there will be an opportunity to resolve merge conflicts, but that is not the case.

It would be nice to have a chance to resolve merge conflicts and then continue the cherry pick.

**Comment by drewbrokke** [comment] 2017-08-10 15:23
@protoEvangelion yes at the moment it's the intended behavior (see https://github.com/drewbrokke/jack/blob/master/src/util/commands.ts#L16).  It would be cool to be able to resolve the conflicts inline, but since it would take quite a bit of planning to implement that interface, I opted to make sure that your history remained intact after a failed cherry-pick in the mean-time.

One thing that could facilitate this moving this feature forward is to know what the options there are for resolving merge conflicts via the command-line.  Git may even have something built-in. If you find something, please link to it here 👍 

I'm going to leave this ticket open as a reminder to myself to look into it.

**Comment by protoEvangelion** [comment] 2017-08-10 16:42
All of the solutions I found involve using some kind of text editor.

Even if that is a text editor cli, we would have to make the assumption that the user has that editor installed.

So the only viable option I see to achieve this is to create a custom inline editor like you mentioned.

But I am wondering if that is overkill.

It makes more sense to allow jack to behave the same way a normal `git cherry-pick` would behave.  Which is to pause the merge if there are conflicts and then allow the user to make the decision whether or not to **merge** or **abort**.

And this way they could use the text editor of their choice without being forced to resolve merge conflicts inline.

**Comment by jwu910** [comment] 2017-08-11 16:43
Would it be possible to allow Jack to wait / watch for a save file similar to how git operates which gives the user freedom to use whichever text editor they prefer?

**Comment by drewbrokke** [comment] 2017-08-14 22:16
I'm going to close this one as a Won't Fix for now, since I'd like to leave it up to the user to decide how they want to resolve merge conflicts or errors.  In the case of trying to cherry-pick a commit that already exists on the current branch, I want the failure to intrude as little as possible in the overall experience of normal jack usage.

**Closed as completed by drewbrokke** 2017-08-14 22:16 UTC
Labels: enhancement, help wanted, wontfix
